project:
  type: book
  output-dir: docs

book:
  title: "Monte Carlo Methods Lecture Notes"
  author: "Apurva Nakade"
  sidebar:
    style: docked
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/apurvanakade/Monte-Carlo-Methods
        aria-label: GitHub
        id: report-issue-link # Not working
  open-graph: true
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - part: chapters/estimation/index.qmd
      chapters:
        - chapters/estimation/estimating_pi.qmd
        - chapters/estimation/integrals.qmd
    - part: chapters/sampling/index.qmd
      chapters:
        - chapters/sampling/rng.qmd
        - chapters/sampling/discrete.qmd
        - chapters/sampling/inverse_transform.qmd
        - chapters/sampling/other_distributions.qmd
        - chapters/sampling/accept_reject.qmd
        - chapters/sampling/gibbs_2d.qmd
        - chapters/sampling/mh.qmd
    - chapters/variance_reduction.qmd
    - part: "Applications"
      chapters:
        - chapters/applications/SDE.qmd
        - chapters/applications/ising.qmd
        - chapters/applications/mmn.qmd
        - chapters/applications/bootstrap.qmd
    - part: "Advanced Topics"
      chapters:
        - chapters/dynamical/kalman_filters.qmd
        - chapters/dynamical/particle_filters.qmd
    - part: "Optimization"
      chapters:
        - chapters/optimization/index.qmd
        - chapters/optimization/simulated_annealing.qmd
        - chapters/optimization/cross_entropy.qmd
    - chapters/references.qmd
  appendices:
    - appendices/probability.qmd
    - appendices/markov_chains.qmd
  page-footer: "Â© 2025 Apurva Nakade. All rights reserved."


bibliography:
  references.bib

format:
  html:
    reader-mode: true
    theme:
      light: [cosmo, brand]
      dark: [superhero, brand]
    css: 
      - style.css
    include-before-body: header-scripts.html
    documentclass: scrreprt
    bread-crumbs: true
    back-to-top-navigation: true
    


execute:
  echo: false
  cache: true
